# Generated by Django 5.2.6 on 2025-09-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0002_itemvariant_itemvariantdocument_itemvariantimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='erpsettings',
            name='deal_pipeline',
        ),
        migrations.RemoveField(
            model_name='erpsettings',
            name='lead_note_doctype',
        ),
        migrations.AlterField(
            model_name='erpsettings',
            name='lead_doctype',
            field=models.CharField(default='Visitor Information', max_length=60),
        ),
        migrations.AlterField(
            model_name='erpsettings',
            name='naming_series',
            field=models.CharField(blank=True, default='.FY.EXPO.####', max_length=120),
        ),
    ]
