# Generated by Django 5.2.6 on 2025-09-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0003_remove_erpsettings_deal_pipeline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpsettings',
            name='contactus_page',
            field=models.CharField(blank=True, default='Contact Us (Website Page)', max_length=120),
        ),
        migrations.AlterField(
            model_name='erpsettings',
            name='status',
            field=models.CharField(blank=True, default='Open', max_length=120),
        ),
    ]
