# Generated by Django 5.2.6 on 2025-09-19 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0004_erpsettings_contactus_page_alter_erpsettings_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_rules', to='configurator.item')),
                ('required_choices', models.ManyToManyField(blank=True, related_name='variant_rules', to='configurator.choice')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='configurator.itemvariant')),
            ],
            options={
                'verbose_name': 'Variant Rule',
                'verbose_name_plural': 'Variant Rules',
            },
        ),
    ]
