# Generated by Django 5.2.6 on 2025-09-19 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0005_variantrule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariantRule',
        ),
    ]
