# Generated by Django 5.2.6 on 2025-09-24 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0006_delete_variantrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceRevealsQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revealed_by', to='configurator.question')),
                ('trigger_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reveals', to='configurator.choice')),
            ],
            options={
                'unique_together': {('trigger_choice', 'target_question')},
            },
        ),
    ]
