# Generated by Django 5.2.6 on 2025-09-24 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0007_choicerevealsquestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChoiceRevealsQuestion',
        ),
    ]
