# Generated by Django 5.2.6 on 2025-09-24 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0008_delete_choicerevealsquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='depends_on',
            field=models.ForeignKey(blank=True, help_text='If set, this question is only shown when the parent’s required choices are selected.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unlocks_children', to='configurator.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='trigger_choices',
            field=models.ManyToManyField(blank=True, help_text='Which choices of the parent question should reveal this one.', related_name='unlocks_questions', to='configurator.choice'),
        ),
    ]
